# Your Solution
version: '3'
services:
 # book-catalog Microservice
  book_catalog:
    image: book_catalog:v1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://sit722projectpart4_user:91sVs60U]f4Qp4tNhc8H1zI0rdoH8n1t@dpg-crnspig8fa8c738ke8ng-a.oregon-postgres.render.com/sit722projectpart4
    restart: "no"

  inventory_management:
    image: inventory_management:v1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://sit722projectpart4_user:91sVs60U]f40p4tNhc8H1zI0rdoH8n1t@dpg-crnspig8fac738ke8ng-a.oregon-postgres.render.com/sit722projectpart4
    restart: "no"